### ISSUE TITLE
Check for updates error

### ISSUE THREAD

**Issue by qbicus** [mitchellurgero/openrsd#45]
There are 2 errors with check for updates:

1) https://github.com/mitchellurgero/openrsd/blob/master/pages/dashboard.php : 99
`} elseif (strpos($c, 'up-to-date') !== false) { `
should be
`} elseif (strpos($c, 'up to date') !== false) {`

2) https://github.com/mitchellurgero/openrsd/blob/master/pages/check.php : 38
`} elseif (strpos($c, 'up-to-date') !== false) {`
should be
`} elseif (strpos($c, 'up to date') !== false) {`

(at least on my machine). The error reported by OpenRSD is:

> On branch master
> Your branch is up to date with 'origin/master'.
> 
> nothing to commit, working tree clean
> 

as you can see up to date not up-to-date is present.

~Q

**Comment by mitchellurgero** [comment]
Thanks for pointing this out! I will take a look when I can. You are also welcome to make a merge/pull request if you feel so inclined.

Thanks again!

**Comment by danmrossi** [comment]
Hi there, i have the "There was an error checking for OpenRSD updates." i am running a rpi v4 with the latest raspbian buster lite build 2019-09-26 ran the usual updates/upgrades and followed your recommended installation routine. What files/screenshots can i give you? sorry if im not asking the right questions, first time poster long time tinkerer :)

**Comment by mitchellurgero** [comment]
@danmrossi I would open a new issue here on GitHub using the following link: https://github.com/mitchellurgero/openrsd/issues/new

And post along with it any logs you feel might be relevant (php logs, apache/nginx logs, etc). Be sure that what you post does not house any sensitive information like a password or email etc.
Screenshot / screen capture of the issue, and how I can replicate it (if possible)

**Comment by danmrossi** [comment]
no worries will do that tomorrow thanks :)

**Comment by mitchellurgero** [comment]
Fixed in:
https://github.com/mitchellurgero/openrsd/commit/a237c6c3f091b6a97a0eaef71ba22603f884523b

and

https://github.com/mitchellurgero/openrsd/commit/96cf6144e3ce0a77abd494063c9f938f7ac631a8

**Comment by mengelsen** [comment]
> Fixed in:
> [a237c6c](https://github.com/mitchellurgero/openrsd/commit/a237c6c3f091b6a97a0eaef71ba22603f884523b)
> 
> and
> 
> [96cf614](https://github.com/mitchellurgero/openrsd/commit/96cf6144e3ce0a77abd494063c9f938f7ac631a8)

I checked the dashboard.php file. It contains the edit referenced in the two commits (listed above). However I am still getting a message on the OpenRSD Dashboard that reads: "There was an error checking for OpenRSD updates".

**Comment by gnanet** [comment]
@mengelsen 

The most important information, that will help find out why the error is shown, is to get the output of `git status`, after you changed into the directory of your openrsd installation:

If you followed the steps of the **Recommended Installation**, use the following command to get into the directory

```
cd /var/www/openrsd
```

then run the one-liner below, and provide the resulting output

```
git fetch && git status
```

**Comment by mengelsen** [comment]
> If you followed the steps of the **Recommended Installation**, use the following command to get into the directory
> 
> ```
> cd /var/www/openrsd
> ```
> 
> then run the one-liner below, and provide the resulting output
> 
> ```
> git fetch && git status
> ```

Yes @gnanet, I installed OpenRSD using the "Recommended Installation" instructions. However I also updated the user/group values within /etc/apache2/apache2.conf. This was referenced within Step #3 of the "Advanced Installation".

Here is the output that was produced after running the commands that you suggested:
```
pi@pi:/var/www/openrsd $ pwd
/var/www/openrsd
pi@pi:/var/www/openrsd $ git fetch && git status
error: cannot open .git/FETCH_HEAD: Permission denied
pi@pi:/var/www/openrsd $ sudo git fetch && git status
Refresh index: 100% (916/916), done.
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean
```
